{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-assertr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/assertr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/assertr/assertr_{{ version }}.tar.gz
  sha256: d7dd657c6e4e4b8604204b9c49e7d4ce6f22e117a3ae6a1ee69b3264d2af23f2

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-dplyr >=0.7.0
    - r-rlang >=0.3.0
  run:
    - r-base
    - r-mass
    - r-dplyr >=0.7.0
    - r-rlang >=0.3.0

test:
  commands:
    - $R -e "library('assertr')"           # [not win]
    - "\"%R%\" -e \"library('assertr')\""  # [win]

about:
  home: https://github.com/ropensci/assertr
  license: MIT
  summary: Provides functionality to assert conditions that have to be met so that errors in data used in analysis pipelines can fail quickly. Similar to 'stopifnot()' but more powerful, friendly, and easier for use in pipelines.
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: assertr
# Type: Package
# Title: Assertive Programming for R Analysis Pipelines
# Version: 2.6
# Authors@R: person("Tony", "Fischetti", email="tony.fischetti@gmail.com", role = c("aut", "cre"))
# Description: Provides functionality to assert conditions that have to be met so that errors in data used in analysis pipelines can fail quickly. Similar to 'stopifnot()' but more powerful, friendly, and easier for use in pipelines.
# URL: https://github.com/ropensci/assertr
# BugReports: https://github.com/ropensci/assertr/issues
# License: MIT + file LICENSE
# ByteCompile: TRUE
# LazyData: TRUE
# Depends: R (>= 3.1.0)
# Imports: dplyr (>= 0.7.0), MASS, stats, utils, rlang (>= 0.3.0)
# Suggests: knitr, testthat, magrittr
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-01-22 20:24:57 UTC; tonyfischetti
# Author: Tony Fischetti [aut, cre]
# Maintainer: Tony Fischetti <tony.fischetti@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-22 20:50:06 UTC
