appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: YuQ9PvncU39HB4FfMBOJVNMXTTS/Pb+CZPLiPw0J5enFLOWJM/PNo4/ERyiDtPlVlRLcBbWX5GiX4LkHpb5O30sz1Dpg30MFyHTKSc3iS5kZcQeui9Zjh4A9ZPOaCovARl+XLM3NXEUmHBi6PBNyqzpXFXZFexcBFJxnNznrHGugmspxUr+u0UBG/4NfZ/q7loeoJ6PknkS4czJ+Q/66U+h4fEWiLMQbQIku/bhT5DAzTO8NzQYL9+o0oU05vWZW3yrhcAomJDY7tb3NQlg+UEhUdLelBZxzWjlwvQc52nBfeI401ENs0OeKyqgEOeoSmiyh6metKDSLiMZdG82Iz3phGqRkTX0FSZodHUTPe2mWW5wCne1Oxm3c4BFtZ8AB4JptvEuN98IJ4rvqOvjeGGKRKPvLVSydoLvcWDTzk+kbtK5nJ9W7Z4kCAZ22bDqHWPHTFtZMNbkfAm6dlah9EbyYoh6va0j5+r1r4rwVrZjbc/Oom9xtgpxsMEeAar7Sadrtreecb6FVmsFF2MFp/e6YjOJ/zpE2N9hWa+VyXqVZY5qaj/DfY6gpIstGHr6l/uaf13cMDy8i6Gcj/ilKU9HOsEy6cxqqkGqeU0LaJT7XLiDTO8wYl0w1/dBZ7wUE1BIRyovDTou8tScGLI71VCI3TDmIP+Q3rA5vVcI+iCE=
