travis:
  secure:
    BINSTAR_TOKEN: l++ZpLCi4ayxEGifoZd6ST5DG4jC5RlaKTNzVKesq4z8RkOk7Uo7SFCon4adkp8R2i560PtILUd/tS/Vz4Qw3Jvq8lBcynWmfcCBqk4hQtTriUsXGR8C4bjRmO0GNZITA8i88yj9W8wtyP7pZt7Yv3Bq2AUOO7iiN1T47dhmsEDB9MeG23WGwqbpbfcrrhKW//8vhFPL6MiE2yPOchurKS408mTNqiug/W8/t1h2GJFbjylU2ZPw3PueUggAhcdwi9ID800JzU94dPUqMBvZxrKiNbOlVg+a7qUf/Rclo/zAwWfYZPDjmmd27DOA5hBWH0QlSgG2I4vBXPghdRj9WdIfB+QNBZhoYgbTfaq3tbLCU9w/FHSTQ/PBoSbXyFxyRGPYzNEq2XkiGSITZYGZuRDGSMHtZEuCZvu5cHk+HzX8N0yPgjAFHTZWxg2uTd3sWOKU/OBAmFVmOzdzMBynKQq8RoNgusvuwSd1+JpSjOq6FlGfs+LDF6nirAekVy4qvwN4+szcqTLgXr4v0U15afKNDk/VjK59TVt/A+BLR6wHE9DEqRoFg+JnzBWNBehsJ0tz3ALKqYFKj+8Nsm7LE+gsnCRuuocEyZB0OyUruWKBgyyXjoqKtn57PipcmV3KCS8qCBs71ewI5djIqJoszPFVylBczt/8KczECIsnFRk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
